import { realpathSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { gitTopLevel, packageRoot } from "./lib/repo-root.js";

/**
 * guard — mechanical backing for two rules the prose kept missing.
 *
 * - `write`/`edit` into the vendored upstream tree (`vendor/mattpocock-skills/`)
 *   or its lock (`skills-lock.json`) is blocked, relative to the repository root
 *   and to the pi-myself package root (in a consuming repo the vendored tree
 *   lives inside the installed package).
 * - `write`/`edit` into generated or runtime state relative to the repository
 *   root (AGENTS.md "Boundaries and Safety": `node_modules/`, `.pi/node_modules/`,
 *   `.pi/git/`, `.pi/npm/`, `.pi/sessions/`, `.pi/task-exits/`, `.pi/artifacts/`,
 *   `.pi/task-session-history.json`) is blocked.
 * - `bash` without a `timeout` gets one: 1800 seconds, or `PI_MYSELF_BASH_TIMEOUT`
 *   (positive finite seconds, read when the extension loads). pi's bash tool has
 *   no default, so a hung command would wedge the session. An explicit timeout
 *   is left exactly as given, including the `0` pi rejects.
 *
 * Paths match on segment boundaries (`vendorx/` is not `vendor/`).
 * No UI dependence: the verdict is the tool result, so it holds in print mode
 * and in task children alike.
 */

interface ProtectedPath {
	/** Path segments relative to the anchor root; a match is this path or anything beneath it. */
	readonly segments: readonly string[];
	readonly what: string;
	readonly instead: string;
}

const VENDORED: readonly ProtectedPath[] = [
	{
		segments: ["vendor", "mattpocock-skills"],
		what: "the vendored upstream mattpocock/skills tree (read-only by rule)",
		instead:
			"propose the change upstream (a PR to mattpocock/skills) or make it in the harness layer (.pi/skills, .pi/extensions, .pi/policy)",
	},
	{
		segments: ["skills-lock.json"],
		what: "the generated lock for the vendored skills",
		instead: "run `npm run sync:skills` to re-clone the vendored tree and rehash the lock",
	},
];

const RUNTIME_STATE_INSTEAD = "it is generated by npm or pi at runtime and is overwritten; change its source or configuration instead";

const RUNTIME_STATE: readonly ProtectedPath[] = [
	["node_modules"],
	[".pi", "node_modules"],
	[".pi", "git"],
	[".pi", "npm"],
	[".pi", "sessions"],
	[".pi", "task-exits"],
	[".pi", "artifacts"],
	[".pi", "task-session-history.json"],
].map((segments) => ({ segments, what: "generated runtime state", instead: RUNTIME_STATE_INSTEAD }));

const DEFAULT_BASH_TIMEOUT_SECONDS = 1800;

function bashTimeoutFromEnv(): number {
	const value = Number(process.env.PI_MYSELF_BASH_TIMEOUT);
	return Number.isFinite(value) && value > 0 ? value : DEFAULT_BASH_TIMEOUT_SECONDS;
}

/**
 * Resolve a tool path the way pi's write/edit tools do (`resolveToCwd`): a leading `@` is stripped, `~` expands,
 * a `file://` URL becomes its path, relative paths join `cwd`.
 */
function resolveToolPath(path: string, cwd: string): string {
	let p = path.startsWith("@") ? path.slice(1) : path;
	if (p === "~") p = homedir();
	else if (p.startsWith("~/")) p = join(homedir(), p.slice(2));
	else if (p.startsWith("file://")) p = fileURLToPath(p);
	return isAbsolute(p) ? resolve(p) : resolve(cwd, p);
}

/** The real path of the deepest existing ancestor, with the not-yet-existing tail re-attached. */
function canonical(path: string): string {
	const tail: string[] = [];
	let current = path;
	for (;;) {
		try {
			// .native returns the on-disk case: on a case-insensitive disk (macOS),
			// `VENDOR/...` is the real `vendor/...`, and the plain realpath keeps the typed case.
			return join(realpathSync.native(current), ...tail.reverse());
		} catch {
			const parent = dirname(current);
			if (parent === current) return path;
			tail.push(basename(current));
			current = parent;
		}
	}
}

function segmentsUnder(root: string, target: string): string[] | undefined {
	const rel = relative(root, target);
	if (rel === "" || rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) return undefined;
	return rel.split(sep);
}

/** macOS and Windows disks fold case by default: `VENDOR` and `vendor` are one folder there, including one
 * that does not exist yet (realpath keeps a missing tail's typed case). A case-sensitive volume on those
 * systems only makes the guard refuse a differently cased look-alike, never miss the real path. */
const FOLDS_CASE = process.platform === "darwin" || process.platform === "win32";
const sameSegment = (a: string | undefined, b: string): boolean => (FOLDS_CASE ? a?.toLowerCase() === b.toLowerCase() : a === b);

function startsWithSegments(segments: readonly string[], prefix: readonly string[]): boolean {
	return prefix.length <= segments.length && prefix.every((segment, i) => sameSegment(segments[i], segment));
}

function findProtected(targets: readonly string[], roots: readonly string[], rules: readonly ProtectedPath[]): ProtectedPath | undefined {
	for (const root of roots) {
		for (const target of targets) {
			const segments = segmentsUnder(root, target);
			if (!segments) continue;
			const rule = rules.find((r) => startsWithSegments(segments, r.segments));
			if (rule) return rule;
		}
	}
	return undefined;
}

/** Both spellings of a root: as given and with symlinks resolved (macOS tmp dirs, symlinked checkouts). */
function spellings(path: string): string[] {
	const real = canonical(path);
	return real === path ? [path] : [path, real];
}

/** The extension, protecting the vendored tree inside the package at `pkgRoot` as well as the repository's own. */
export function createGuardExtension(pkgRoot: string): (pi: ExtensionAPI) => void {
	return (pi) => {
		const bashTimeout = bashTimeoutFromEnv();
		const repoRootCache = new Map<string, string[]>();
		const repoRootsOf = (cwd: string): string[] => {
			let roots = repoRootCache.get(cwd);
			if (roots === undefined) {
				roots = spellings(gitTopLevel(cwd) ?? resolve(cwd));
				repoRootCache.set(cwd, roots);
			}
			return roots;
		};
		const packageRoots = spellings(resolve(pkgRoot));

		pi.on("tool_call", (event, ctx) => {
			// Compared by name, not `isToolCallEventType`: that is a runtime import of an optional peer dependency.
			if (event.toolName === "bash") {
				const input = event.input as { timeout?: unknown };
				if (input.timeout === undefined) input.timeout = bashTimeout;
				return undefined;
			}
			if (event.toolName !== "write" && event.toolName !== "edit") return undefined;
			const path = (event.input as { path?: unknown }).path;
			if (typeof path !== "string" || path === "") return undefined;
			const lexical = resolveToolPath(path, ctx.cwd);
			const targets = [...new Set([lexical, resolveToolPath(path, canonical(ctx.cwd)), canonical(lexical)])];
			const repoRoots = repoRootsOf(ctx.cwd);
			const rule = findProtected(targets, [...repoRoots, ...packageRoots], VENDORED) ?? findProtected(targets, repoRoots, RUNTIME_STATE);
			if (!rule) return undefined;
			return { block: true, reason: `pi-myself guard: ${path} is ${rule.what}. Do not ${event.toolName} it; ${rule.instead}.` };
		});
	};
}

export default createGuardExtension(packageRoot(import.meta.url));
